from __future__ import annotations

import re
import secrets
import time
from copy import deepcopy

from music_links_bot.draft_model import normalize_track_draft
from music_links_bot.durable_state import delete_value, read_json
from music_links_bot.kvstore import KVStore
from music_links_bot.state_mutations import StateConflictError, mutate_json

DRAFT_TTL_SECONDS = 7 * 24 * 3600
SAVED_DRAFT_TTL_SECONDS = 90 * 24 * 3600
MAX_MEMORY_DRAFTS = 300
SELECTION_TTL_SECONDS = 15 * 60
MAX_MEMORY_SELECTIONS = 300
RETRY_TTL_SECONDS = 30 * 60
STATE_ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")


def remember_bounded(
    items: dict,
    key: object,
    value: object,
    *,
    max_size: int,
) -> None:
    """Refresh a warm-instance value without allowing unbounded growth."""
    if max_size < 1:
        raise ValueError("max_size must be positive")
    items.pop(key, None)
    while len(items) >= max_size:
        items.pop(next(iter(items)))
    items[key] = value


def valid_state_id(value: object) -> bool:
    """Accept only compact IDs generated by the bot itself."""
    return isinstance(value, str) and STATE_ID_RE.fullmatch(value) is not None


async def store_draft(context, draft_id: str, draft: dict) -> None:
    original = draft
    normalized = normalize_track_draft(draft)
    if normalized is not None:
        draft = normalized
    draft["editor_draft_id"] = draft_id
    if "original_state" not in draft and not draft.get("revision"):
        from music_links_bot.bot_editor_state import setting_snapshot

        draft["original_state"] = setting_snapshot(draft)
    kv: KVStore | None = context.application.bot_data.get("kv_store")
    ttl = SAVED_DRAFT_TTL_SECONDS if draft.get("saved_at") else DRAFT_TTL_SECONDS
    draft["expires_at"] = int(time.time()) + ttl
    revision = int(draft.get("revision") or 0)

    def update(current):
        current_revision = int((current or {}).get("revision") or 0)
        if current_revision != revision or (current is None and revision):
            raise StateConflictError("This draft has changed; reopen it")
        return {**draft, "revision": revision + 1}

    if kv is not None:
        draft = await mutate_json(kv, f"draft:{draft_id}", update, ttl_seconds=ttl)
    else:
        draft = update(context.application.bot_data.get("drafts", {}).get(draft_id))
    original.update(draft)
    drafts: dict = context.application.bot_data.setdefault("drafts", {})
    remember_bounded(
        drafts,
        draft_id,
        deepcopy(draft),
        max_size=MAX_MEMORY_DRAFTS,
    )


async def load_draft(context, draft_id: str) -> dict | None:
    if not valid_state_id(draft_id):
        return None
    drafts: dict = context.application.bot_data.setdefault("drafts", {})
    kv: KVStore | None = context.application.bot_data.get("kv_store")
    draft = deepcopy(drafts.get(draft_id)) if kv is None else None
    if draft and draft.get("expires_at") and draft["expires_at"] <= time.time():
        drafts.pop(draft_id, None)
        return None
    if isinstance(draft, dict):
        normalized = normalize_track_draft(draft)
        if normalized is not None:
            normalized["editor_draft_id"] = draft_id
            drafts[draft_id] = deepcopy(normalized)
            return normalized
        return draft

    if kv is None:
        return None
    draft = await read_json(kv, f"draft:{draft_id}")
    normalized = normalize_track_draft(draft)
    if normalized is not None:
        normalized["editor_draft_id"] = draft_id
        remember_bounded(
            drafts,
            draft_id,
            deepcopy(normalized),
            max_size=MAX_MEMORY_DRAFTS,
        )
        return normalized
    drafts.pop(draft_id, None)
    return None


async def delete_draft(context, draft_id: str) -> None:
    if not valid_state_id(draft_id):
        return
    kv: KVStore | None = context.application.bot_data.get("kv_store")
    if kv is not None:
        await delete_value(kv, f"draft:{draft_id}")
    context.application.bot_data.setdefault("drafts", {}).pop(draft_id, None)


async def store_search_selection(
    context,
    *,
    user_id: int,
    query: str,
    urls: list[str],
) -> str:
    selection_id = secrets.token_hex(5)
    payload = {"user_id": user_id, "query": query, "urls": urls}
    selections: dict = context.application.bot_data.setdefault("search_selections", {})
    remember_bounded(
        selections,
        selection_id,
        payload,
        max_size=MAX_MEMORY_SELECTIONS,
    )
    kv: KVStore | None = context.application.bot_data.get("kv_store")
    if kv is not None:
        await kv.set_json(
            f"selection:v1:{selection_id}",
            payload,
            ttl_seconds=SELECTION_TTL_SECONDS,
        )
    return selection_id


async def load_search_selection(context, selection_id: str) -> dict | None:
    if not valid_state_id(selection_id):
        return None
    selections: dict = context.application.bot_data.setdefault("search_selections", {})
    payload = selections.get(selection_id)
    if isinstance(payload, dict):
        return payload

    kv: KVStore | None = context.application.bot_data.get("kv_store")
    payload = await kv.get_json(f"selection:v1:{selection_id}") if kv else None
    if isinstance(payload, dict):
        remember_bounded(
            selections,
            selection_id,
            payload,
            max_size=MAX_MEMORY_SELECTIONS,
        )
        return payload
    return None


async def store_retry_sources(
    context,
    *,
    user_id: int,
    urls: list[str],
    completed: dict | None = None,
) -> str:
    retry_id = secrets.token_hex(5)
    payload = {
        "user_id": int(user_id),
        "urls": [str(url) for url in urls if url][:10],
    }
    if completed:
        payload["completed"] = completed
    retries: dict = context.application.bot_data.setdefault("retry_sources", {})
    remember_bounded(
        retries,
        retry_id,
        payload,
        max_size=MAX_MEMORY_SELECTIONS,
    )
    kv: KVStore | None = context.application.bot_data.get("kv_store")
    if kv is not None:
        await kv.set_json(
            f"retry:v1:{retry_id}",
            payload,
            ttl_seconds=RETRY_TTL_SECONDS,
        )
    return retry_id


async def load_retry_sources(context, retry_id: str) -> dict | None:
    if not valid_state_id(retry_id):
        return None
    retries: dict = context.application.bot_data.setdefault("retry_sources", {})
    payload = retries.get(retry_id)
    if isinstance(payload, dict):
        return payload

    kv: KVStore | None = context.application.bot_data.get("kv_store")
    payload = await kv.get_json(f"retry:v1:{retry_id}") if kv else None
    if isinstance(payload, dict):
        remember_bounded(
            retries,
            retry_id,
            payload,
            max_size=MAX_MEMORY_SELECTIONS,
        )
        return payload
    return None


async def load_drafts(context, draft_ids: list[str]) -> list[dict | None]:
    """One confirmed Redis request for the library, preserving missing slots."""
    ids = [value for value in draft_ids if valid_state_id(value)][:60]
    kv = context.application.bot_data.get("kv_store")
    reader = getattr(kv, "mget_json_required", None)
    if reader is None:
        return [await load_draft(context, value) for value in ids]
    values = await reader([f"draft:{value}" for value in ids])
    result = []
    for draft_id, value in zip(ids, values, strict=True):
        draft = normalize_track_draft(value)
        if draft is not None:
            draft["editor_draft_id"] = draft_id
        result.append(draft)
    return result
